-- Добавить vessel_type в vessel_specs (только 49 судов, уже есть в таблице)
ALTER TABLE vessel_specs ADD COLUMN IF NOT EXISTS vessel_type text;

UPDATE vessel_specs SET vessel_type = 'сбс' WHERE vessel_name = 'Рубин';
UPDATE vessel_specs SET vessel_type = 'сб' WHERE vessel_name = 'Тиман';
UPDATE vessel_specs SET vessel_type = 'сб' WHERE vessel_name = 'Узон';
UPDATE vessel_specs SET vessel_type = 'сб' WHERE vessel_name = 'Гроза';
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE vessel_name = 'Артемис Оффшор';
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE vessel_name = 'Берингов Пролив';
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE vessel_name = 'Мурман';
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE vessel_name = 'Финвал';
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE vessel_name = 'Умка';
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE vessel_name = 'Нарвал';
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE vessel_name = 'Бахтемир';
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE vessel_name = 'Бейсуг';
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE vessel_name = 'Калас';
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE vessel_name = 'Пильтун';
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE vessel_name = 'Спасатель Демидов';
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE vessel_name = 'Спасатель Заборщиков';
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE vessel_name = 'Спасатель Ильин';
UPDATE vessel_specs SET vessel_type = 'сб' WHERE vessel_name = 'Оберон';
UPDATE vessel_specs SET vessel_type = 'скб' WHERE vessel_name = 'Айруп';
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE vessel_name = 'Балтика';
UPDATE vessel_specs SET vessel_type = 'сб' WHERE vessel_name = 'Буран';
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE vessel_name = 'Спасатель Кавдейкин';
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE vessel_name = 'Спасатель Карев';
UPDATE vessel_specs SET vessel_type = 'нис' WHERE vessel_name = 'Балтийский исследователь';
UPDATE vessel_specs SET vessel_type = 'сбс' WHERE vessel_name = 'Светломор-3';
UPDATE vessel_specs SET vessel_type = 'сбс' WHERE vessel_name = 'Лазурит';
UPDATE vessel_specs SET vessel_type = 'сбс' WHERE vessel_name = 'Капитан Беклемишев';
UPDATE vessel_specs SET vessel_type = 'сбс' WHERE vessel_name = 'Эпрон';
UPDATE vessel_specs SET vessel_type = 'нис' WHERE vessel_name = 'Игорь Ильин';
UPDATE vessel_specs SET vessel_type = 'нис' WHERE vessel_name = 'Виктор Буйницкий';
UPDATE vessel_specs SET vessel_type = 'сбс' WHERE vessel_name = 'Меркурий';
UPDATE vessel_specs SET vessel_type = 'сб' WHERE vessel_name = 'Пенай';
UPDATE vessel_specs SET vessel_type = 'мвс' WHERE vessel_name = 'Ростов Великий';
UPDATE vessel_specs SET vessel_type = 'мвс' WHERE vessel_name = 'Стольный град Ярославль';
UPDATE vessel_specs SET vessel_type = 'мвс' WHERE vessel_name = 'Углич';
UPDATE vessel_specs SET vessel_type = 'сб' WHERE vessel_name = 'Печак';
UPDATE vessel_specs SET vessel_type = 'сб' WHERE vessel_name = 'Тепсей';
UPDATE vessel_specs SET vessel_type = 'сб' WHERE vessel_name = 'Бэй';
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE vessel_name = 'Сейвал';
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE vessel_name = 'Сивуч';
UPDATE vessel_specs SET vessel_type = 'сбс' WHERE vessel_name = 'Капитан Мартышкин';
UPDATE vessel_specs SET vessel_type = 'сбс' WHERE vessel_name = 'Нефтегаз-55';
UPDATE vessel_specs SET vessel_type = 'сбс' WHERE vessel_name = 'Отто Шмидт';
UPDATE vessel_specs SET vessel_type = 'сбс' WHERE vessel_name = 'Ясный';
UPDATE vessel_specs SET vessel_type = 'нис' WHERE vessel_name = 'Импульс';
UPDATE vessel_specs SET vessel_type = 'сб' WHERE vessel_name = 'Союз';
UPDATE vessel_specs SET vessel_type = 'сб' WHERE vessel_name = 'Амбер';
UPDATE vessel_specs SET vessel_type = 'сб' WHERE vessel_name = 'Руби';
UPDATE vessel_specs SET vessel_type = 'скб' WHERE vessel_name = 'Капитан Мишин';