-- Миграция: добавить vessel_type в vessel_specs и заполнить из fleet.xlsx
ALTER TABLE vessel_specs ADD COLUMN IF NOT EXISTS vessel_type text;

UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Айруп');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Александр Сизонцев');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Алиот');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('Альтаир');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Альфард');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Амбер');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Анатолий Веретехин');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Анатолий Ткачев');
UPDATE vessel_specs SET vessel_type = 'сквп' WHERE lower(vessel_name) = lower('Арго');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Арнеб');
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE lower(vessel_name) = lower('Артемис Оффшор');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('Артик');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('АСПТР-5');
UPDATE vessel_specs SET vessel_type = 'баржа' WHERE lower(vessel_name) = lower('АСПТР-7');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Б-104');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Б-1214');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Б-123');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Б-245');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Б-407');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Б-505');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Б-507');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Б-508');
UPDATE vessel_specs SET vessel_type = 'мвс' WHERE lower(vessel_name) = lower('Б-706');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Байкал');
UPDATE vessel_specs SET vessel_type = 'нис' WHERE lower(vessel_name) = lower('Балтийский Исследователь');
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE lower(vessel_name) = lower('Балтика');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('Барс');
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE lower(vessel_name) = lower('Бахтемир');
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE lower(vessel_name) = lower('Бейсуг');
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE lower(vessel_name) = lower('Берингов пролив');
UPDATE vessel_specs SET vessel_type = 'баржа' WHERE lower(vessel_name) = lower('БМС-001');
UPDATE vessel_specs SET vessel_type = 'баржа' WHERE lower(vessel_name) = lower('БМС-002');
UPDATE vessel_specs SET vessel_type = 'баржа' WHERE lower(vessel_name) = lower('БП-2');
UPDATE vessel_specs SET vessel_type = 'баржа' WHERE lower(vessel_name) = lower('БПБ-001');
UPDATE vessel_specs SET vessel_type = 'брандвахта' WHERE lower(vessel_name) = lower('БР-203');
UPDATE vessel_specs SET vessel_type = 'баржа' WHERE lower(vessel_name) = lower('БС-220');
UPDATE vessel_specs SET vessel_type = 'баржа' WHERE lower(vessel_name) = lower('БС-320');
UPDATE vessel_specs SET vessel_type = 'баржа' WHERE lower(vessel_name) = lower('БС-510');
UPDATE vessel_specs SET vessel_type = 'баржа' WHERE lower(vessel_name) = lower('БС-512');
UPDATE vessel_specs SET vessel_type = 'баржа' WHERE lower(vessel_name) = lower('БС-513');
UPDATE vessel_specs SET vessel_type = 'баржа' WHERE lower(vessel_name) = lower('БС-717');
UPDATE vessel_specs SET vessel_type = 'баржа' WHERE lower(vessel_name) = lower('БС-718');
UPDATE vessel_specs SET vessel_type = 'баржа' WHERE lower(vessel_name) = lower('БС-928');
UPDATE vessel_specs SET vessel_type = 'сбп' WHERE lower(vessel_name) = lower('БТ-566');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Буран');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('Быстрый');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Бэй');
UPDATE vessel_specs SET vessel_type = 'рвк' WHERE lower(vessel_name) = lower('В-221');
UPDATE vessel_specs SET vessel_type = 'рвк' WHERE lower(vessel_name) = lower('В-710');
UPDATE vessel_specs SET vessel_type = 'рвк' WHERE lower(vessel_name) = lower('В-719');
UPDATE vessel_specs SET vessel_type = 'рвк' WHERE lower(vessel_name) = lower('Валентин Подгорный');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Валерий Барский');
UPDATE vessel_specs SET vessel_type = 'нис' WHERE lower(vessel_name) = lower('Виктор Буйницкий');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Виктор Петров');
UPDATE vessel_specs SET vessel_type = 'рвк' WHERE lower(vessel_name) = lower('Водолаз Грицай');
UPDATE vessel_specs SET vessel_type = 'рвк' WHERE lower(vessel_name) = lower('Водолаз Денисов');
UPDATE vessel_specs SET vessel_type = 'рвк' WHERE lower(vessel_name) = lower('Водолаз Зубченко');
UPDATE vessel_specs SET vessel_type = 'рвк' WHERE lower(vessel_name) = lower('Водолаз Зюляев');
UPDATE vessel_specs SET vessel_type = 'рвк' WHERE lower(vessel_name) = lower('Водолаз Кузьминых');
UPDATE vessel_specs SET vessel_type = 'рвк' WHERE lower(vessel_name) = lower('Водолаз Литвин');
UPDATE vessel_specs SET vessel_type = 'рвк' WHERE lower(vessel_name) = lower('Водолаз Малеев');
UPDATE vessel_specs SET vessel_type = 'рвк' WHERE lower(vessel_name) = lower('Водолаз Печкуров');
UPDATE vessel_specs SET vessel_type = 'рвк' WHERE lower(vessel_name) = lower('Водолаз Сазонов');
UPDATE vessel_specs SET vessel_type = 'рвк' WHERE lower(vessel_name) = lower('Водолаз Сташков');
UPDATE vessel_specs SET vessel_type = 'рвк' WHERE lower(vessel_name) = lower('Водолаз Чебаненко');
UPDATE vessel_specs SET vessel_type = 'мвс' WHERE lower(vessel_name) = lower('Водолаз-14');
UPDATE vessel_specs SET vessel_type = 'рвк' WHERE lower(vessel_name) = lower('Водолаз-31');
UPDATE vessel_specs SET vessel_type = 'рвк' WHERE lower(vessel_name) = lower('Водолаз-32');
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE lower(vessel_name) = lower('Воевода');
UPDATE vessel_specs SET vessel_type = 'рвк' WHERE lower(vessel_name) = lower('Волна');
UPDATE vessel_specs SET vessel_type = 'рвк' WHERE lower(vessel_name) = lower('ВРД-1025');
UPDATE vessel_specs SET vessel_type = 'рвк' WHERE lower(vessel_name) = lower('ВРД-1170');
UPDATE vessel_specs SET vessel_type = 'рвк' WHERE lower(vessel_name) = lower('ВРД-1505');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Выборг');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Геннадий Кожухов');
UPDATE vessel_specs SET vessel_type = 'нсс' WHERE lower(vessel_name) = lower('Григорий Каштаков');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Гроза');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Дерзкий');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Евгений Морозов');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Залив');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Зенит');
UPDATE vessel_specs SET vessel_type = 'нис' WHERE lower(vessel_name) = lower('Игорь Ильин');
UPDATE vessel_specs SET vessel_type = 'нис' WHERE lower(vessel_name) = lower('Импульс');
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE lower(vessel_name) = lower('Калас');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Капитан Балашов');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Капитан Барабаш');
UPDATE vessel_specs SET vessel_type = 'сбс' WHERE lower(vessel_name) = lower('Капитан Беклемишев');
UPDATE vessel_specs SET vessel_type = 'сбс' WHERE lower(vessel_name) = lower('Капитан Мартышкин');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Капитан Мишин');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Капитан Оходов');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Карат');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Карат-2');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Карат-3');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('Карелия');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('Катран');
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE lower(vessel_name) = lower('Керченский пролив');
UPDATE vessel_specs SET vessel_type = 'сбп' WHERE lower(vessel_name) = lower('Колонок-57');
UPDATE vessel_specs SET vessel_type = 'сбп' WHERE lower(vessel_name) = lower('Колонок-99');
UPDATE vessel_specs SET vessel_type = 'кран' WHERE lower(vessel_name) = lower('КПЛ-16-10');
UPDATE vessel_specs SET vessel_type = 'сбс' WHERE lower(vessel_name) = lower('Лазурит');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('ЛАРН-1');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('ЛАРН-1');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('ЛАРН-2');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('ЛАРН-3');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('ЛАРН-4');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('Лоцман Гаркуша');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Максим Колосов');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Маркаб');
UPDATE vessel_specs SET vessel_type = 'баржа' WHERE lower(vessel_name) = lower('МГ-101');
UPDATE vessel_specs SET vessel_type = 'сбс' WHERE lower(vessel_name) = lower('Меркурий');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('Метель');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('Механик Лепилин');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Мизар');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('МОБ-20');
UPDATE vessel_specs SET vessel_type = 'спк' WHERE lower(vessel_name) = lower('Могучий');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('МРК-1000');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('МСС-01');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('МСС-02');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('МСС-03');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('МСС-04');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('МСС-05');
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE lower(vessel_name) = lower('Мурман');
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE lower(vessel_name) = lower('Нарвал');
UPDATE vessel_specs SET vessel_type = 'рвк' WHERE lower(vessel_name) = lower('Нерей');
UPDATE vessel_specs SET vessel_type = 'сбс' WHERE lower(vessel_name) = lower('Нефтегаз-55');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Нефтесборщик-1');
UPDATE vessel_specs SET vessel_type = 'нсс' WHERE lower(vessel_name) = lower('Нефтесборщик-2');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Николай Бурков');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Николай Семенченко');
UPDATE vessel_specs SET vessel_type = 'нсс' WHERE lower(vessel_name) = lower('НМС-17');
UPDATE vessel_specs SET vessel_type = 'нсс' WHERE lower(vessel_name) = lower('НМС-26');
UPDATE vessel_specs SET vessel_type = 'нсс' WHERE lower(vessel_name) = lower('НМС-К');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Оберон');
UPDATE vessel_specs SET vessel_type = 'сбс' WHERE lower(vessel_name) = lower('Отто Шмидт');
UPDATE vessel_specs SET vessel_type = 'баржа' WHERE lower(vessel_name) = lower('П-201');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Пенай');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Печак');
UPDATE vessel_specs SET vessel_type = 'баржа' WHERE lower(vessel_name) = lower('Пикник');
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE lower(vessel_name) = lower('Пильтун');
UPDATE vessel_specs SET vessel_type = 'кран' WHERE lower(vessel_name) = lower('ПК-108');
UPDATE vessel_specs SET vessel_type = 'кран' WHERE lower(vessel_name) = lower('ПК-109');
UPDATE vessel_specs SET vessel_type = 'кран' WHERE lower(vessel_name) = lower('ПК-1202');
UPDATE vessel_specs SET vessel_type = 'кран' WHERE lower(vessel_name) = lower('ПК-1204');
UPDATE vessel_specs SET vessel_type = 'кран' WHERE lower(vessel_name) = lower('ПК-205');
UPDATE vessel_specs SET vessel_type = 'кран' WHERE lower(vessel_name) = lower('ПК-206');
UPDATE vessel_specs SET vessel_type = 'кран' WHERE lower(vessel_name) = lower('ПК-307');
UPDATE vessel_specs SET vessel_type = 'кран' WHERE lower(vessel_name) = lower('ПК-312');
UPDATE vessel_specs SET vessel_type = 'кран' WHERE lower(vessel_name) = lower('ПК-313');
UPDATE vessel_specs SET vessel_type = 'кран' WHERE lower(vessel_name) = lower('ПК-407');
UPDATE vessel_specs SET vessel_type = 'кран' WHERE lower(vessel_name) = lower('ПК-506');
UPDATE vessel_specs SET vessel_type = 'кран' WHERE lower(vessel_name) = lower('ПК-508');
UPDATE vessel_specs SET vessel_type = 'кран' WHERE lower(vessel_name) = lower('ПК-712');
UPDATE vessel_specs SET vessel_type = 'кран' WHERE lower(vessel_name) = lower('ПК-714');
UPDATE vessel_specs SET vessel_type = 'кран' WHERE lower(vessel_name) = lower('ПК-716');
UPDATE vessel_specs SET vessel_type = 'кран' WHERE lower(vessel_name) = lower('ПК-717');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Плотовод-685');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Подводник');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Портовый-1');
UPDATE vessel_specs SET vessel_type = 'баржа' WHERE lower(vessel_name) = lower('ППС-101');
UPDATE vessel_specs SET vessel_type = 'сбп' WHERE lower(vessel_name) = lower('Прибрежный');
UPDATE vessel_specs SET vessel_type = 'причал' WHERE lower(vessel_name) = lower('ПРП-20 №40');
UPDATE vessel_specs SET vessel_type = 'причал' WHERE lower(vessel_name) = lower('ПРП-4');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Резвый');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('РК-700');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('РК-700-1');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('РК-700-2');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('РК-700-3');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('РМС 09-30');
UPDATE vessel_specs SET vessel_type = 'мвс' WHERE lower(vessel_name) = lower('Ростов Великий');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('РСЯ 06-80 (без рубки)');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('РСЯ 06-82');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('РСЯ 07-52');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('РСЯ 07-53');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Руби');
UPDATE vessel_specs SET vessel_type = 'сбс' WHERE lower(vessel_name) = lower('Рубин');
UPDATE vessel_specs SET vessel_type = 'мвс' WHERE lower(vessel_name) = lower('Рыбинск');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('Самсон');
UPDATE vessel_specs SET vessel_type = 'нсс' WHERE lower(vessel_name) = lower('Сборщик-348');
UPDATE vessel_specs SET vessel_type = 'сбс' WHERE lower(vessel_name) = lower('Светломор-3');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Север-46');
UPDATE vessel_specs SET vessel_type = 'сбп' WHERE lower(vessel_name) = lower('Север-7');
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE lower(vessel_name) = lower('Сейвал');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Сергей Кладько');
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE lower(vessel_name) = lower('Сивуч');
UPDATE vessel_specs SET vessel_type = 'рвк' WHERE lower(vessel_name) = lower('Сигнал');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('Скат');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Союз');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Спасатель Алексюк');
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE lower(vessel_name) = lower('Спасатель Демидов');
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE lower(vessel_name) = lower('Спасатель Заборщиков');
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE lower(vessel_name) = lower('Спасатель Ильин');
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE lower(vessel_name) = lower('Спасатель Кавдейкин');
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE lower(vessel_name) = lower('Спасатель Карев');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('Спасатель-1');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Спасатель-1');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Спасатель-2');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('Спасатель-2');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Спасатель-3');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Спасатель-4');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('Спасатель-5');
UPDATE vessel_specs SET vessel_type = 'кран' WHERE lower(vessel_name) = lower('СПК-19-35');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('Спортис');
UPDATE vessel_specs SET vessel_type = 'мвс' WHERE lower(vessel_name) = lower('Стольный Град Ярославль');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Тепсей');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Тиман');
UPDATE vessel_specs SET vessel_type = 'мвс' WHERE lower(vessel_name) = lower('Углич');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Узон');
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE lower(vessel_name) = lower('Умка');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('УРА-1');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('УРА-2');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('УРА-3');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('УРА-4');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Урал-33');
UPDATE vessel_specs SET vessel_type = 'сб' WHERE lower(vessel_name) = lower('Фавор');
UPDATE vessel_specs SET vessel_type = 'мфасс' WHERE lower(vessel_name) = lower('Финвал');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('Хайтек 85C');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('Хайтек-75-1');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('Хайтек-75-2');
UPDATE vessel_specs SET vessel_type = 'сквп' WHERE lower(vessel_name) = lower('Хивус-10');
UPDATE vessel_specs SET vessel_type = 'пс' WHERE lower(vessel_name) = lower('Часовой');
UPDATE vessel_specs SET vessel_type = 'спк' WHERE lower(vessel_name) = lower('Черноморец-18');
UPDATE vessel_specs SET vessel_type = 'баржа' WHERE lower(vessel_name) = lower('Ш-706');
UPDATE vessel_specs SET vessel_type = 'ск' WHERE lower(vessel_name) = lower('Шельф GTJet');
UPDATE vessel_specs SET vessel_type = 'скб' WHERE lower(vessel_name) = lower('ЭКО-1');
UPDATE vessel_specs SET vessel_type = 'нсс' WHERE lower(vessel_name) = lower('ЭКО-2МС');
UPDATE vessel_specs SET vessel_type = 'сбс' WHERE lower(vessel_name) = lower('Эпрон');
UPDATE vessel_specs SET vessel_type = 'сбс' WHERE lower(vessel_name) = lower('Ясный');